# 1. Identificación y Puerto
spring.application.name=microservicio-inventario
server.port=8081


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/concesionaria_inventario_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 4. Flyway (Migraciones de Base de Datos)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.cloud.compatibility-verifier.enabled=false
eureka.client.enabled=false
spring.cloud.discovery.enabled=false